"""singaporerabbit content factory daily generator.

flow per run:
1. load queue.json, pick next queued topic (or specified --key)
2. generate via claude --print --model sonnet
3. humanizer pass (second claude call)
4. lint
5. on pass: write to src/content/guides/<key>.mdx, commit to auto-drafts/<key>
   branch, push, mark queued -> drafted, TG notify
6. on lint fail: mark queued -> failed, TG notify (don't write)

draft branches are NOT auto-merged. user reviews and merges manually for
the first 30 days. once trust is established, flip AUTO_MERGE = True.

CLI:
  python3 generate.py                # next queued topic
  python3 generate.py --key netherland-dwarf-sg-care
  python3 generate.py --dry-run      # generate to .factory-out/, do not commit
"""
import argparse
import datetime
import json
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
REPO_ROOT = ROOT.parent.parent
sys.path.insert(0, str(ROOT))

from claude_call import ask_claude  # noqa: E402
from lint import lint_post  # noqa: E402
from prompts import build_generation_prompt, build_humanizer_prompt  # noqa: E402

QUEUE_PATH = ROOT / "queue.json"
GUIDES_DIR = REPO_ROOT / "src" / "content" / "guides"
DRY_OUT = ROOT / ".factory-out"
LOG_FILE = ROOT / "logs" / "factory.log"
LOG_FILE.parent.mkdir(parents=True, exist_ok=True)

AUTO_MERGE = False  # if True, factory pushes directly to main. keep False for review-first.


def log(msg: str) -> None:
    ts = datetime.datetime.now().isoformat(timespec="seconds")
    line = f"[{ts}] {msg}"
    print(line)
    with LOG_FILE.open("a") as f:
        f.write(line + "\n")


def load_queue() -> dict:
    return json.loads(QUEUE_PATH.read_text())


def save_queue(q: dict) -> None:
    QUEUE_PATH.write_text(json.dumps(q, indent=2) + "\n")


def pick_topic(queue: dict, key: str | None) -> dict | None:
    topics = queue["topics"]
    if key:
        return next((t for t in topics if t["key"] == key), None)
    return next((t for t in topics if t["status"] == "queued"), None)


def git_run(*args: str, cwd: Path = REPO_ROOT) -> subprocess.CompletedProcess:
    return subprocess.run(["git", *args], cwd=cwd, capture_output=True, text=True, check=False)


def notify(msg: str, title: str = "rabbits factory") -> None:
    notifier = REPO_ROOT / "scripts" / "tg-notify.sh"
    subprocess.run([str(notifier), msg, title], check=False)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--key")
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()

    queue = load_queue()
    topic = pick_topic(queue, args.key)
    if not topic:
        log("no queued topics" if not args.key else f"key {args.key} not found")
        return 1

    log(f"picked {topic['key']} (stream={topic['stream']})")

    today = datetime.date.today().isoformat()
    gen_prompt = build_generation_prompt(topic, today)

    draft = ask_claude(gen_prompt, model="sonnet", timeout=600)
    if not draft:
        log("generation FAILED")
        notify(f"{topic['key']}: generation failed", "rabbits factory")
        return 2

    hum_prompt = build_humanizer_prompt(draft)
    final = ask_claude(hum_prompt, model="sonnet", timeout=600)
    if not final:
        log("humanizer FAILED, using raw draft")
        final = draft

    ok, errors = lint_post(final, expected_title=topic["title"])
    if not ok:
        log(f"lint FAILED for {topic['key']}: {errors}")
        if args.dry_run:
            DRY_OUT.mkdir(parents=True, exist_ok=True)
            (DRY_OUT / f"{topic['key']}.failed.mdx").write_text(final)
        topic["status"] = "failed"
        topic["last_failed"] = today
        topic["last_errors"] = errors[:5]
        save_queue(queue)
        notify(f"{topic['key']}: lint failed ({len(errors)} issues)", "rabbits factory")
        return 3

    if args.dry_run:
        DRY_OUT.mkdir(parents=True, exist_ok=True)
        out_path = DRY_OUT / f"{topic['key']}.mdx"
        out_path.write_text(final)
        log(f"dry-run wrote {out_path}")
        return 0

    # write to repo + commit to auto-drafts branch
    mdx_path = GUIDES_DIR / f"{topic['key']}.mdx"
    if mdx_path.exists():
        log(f"{mdx_path} exists, skipping (queue topic may be stale)")
        topic["status"] = "drafted"
        save_queue(queue)
        return 4

    mdx_path.write_text(final)

    branch = f"auto-drafts/{topic['key']}"
    if AUTO_MERGE:
        branch = "main"

    git_run("checkout", "-B", branch)
    git_run("add", str(mdx_path))
    commit_msg = f"factory: draft {topic['key']} ({topic['stream']})\n\nauto-generated by rabbits factory. review before merging to main.\n\nCo-Authored-By: Claude Opus 4.7 <noreply@anthropic.com>"
    commit_res = git_run("commit", "-m", commit_msg)
    if commit_res.returncode != 0:
        log(f"git commit failed: {commit_res.stderr}")
        notify(f"{topic['key']}: git commit failed", "rabbits factory")
        return 5

    push_res = git_run("push", "-u", "origin", branch)
    if push_res.returncode != 0:
        log(f"git push failed: {push_res.stderr}")
        notify(f"{topic['key']}: git push failed (committed locally)", "rabbits factory")
    else:
        log(f"pushed branch {branch}")

    git_run("checkout", "main")

    topic["status"] = "drafted"
    topic["drafted_at"] = today
    topic["branch"] = branch
    save_queue(queue)

    pr_url = f"https://github.com/Xavierfok/singaporerabbit/compare/main...{branch}"
    notify(f"draft ready: {topic['key']}\nbranch: {branch}\nopen PR: {pr_url}", "rabbits factory")
    log(f"DONE {topic['key']}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
