"""seed 500 new topics into queue.json, dedupe against existing guides + queue.

run: python3 scripts/factory/seed_500.py
"""
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent
REPO = ROOT.parent.parent
QUEUE = ROOT / "queue.json"
GUIDES = REPO / "src" / "content" / "guides"


def slugify(s: str) -> str:
    s = s.lower().strip()
    s = re.sub(r"[^a-z0-9\- ]", "", s)
    s = re.sub(r"\s+", "-", s)
    s = re.sub(r"-+", "-", s)
    return s


# (key, title, stream, schema_type)
TOPICS = [
    # ============= HEALTH: DENTAL (20) =============
    ("rabbit-malocclusion-signs-sg", "spotting rabbit malocclusion early in singapore", "care-deep-dives", "HowTo"),
    ("rabbit-tooth-spurs-when-to-vet", "when tooth spurs need a vet trip, not a wait", "care-deep-dives", "Article"),
    ("rabbit-incisor-trim-cost-sg", "what an incisor trim actually costs in singapore", "vet-comparisons", "Article"),
    ("rabbit-molar-burr-procedure-sg", "molar burring under sedation, what to expect", "care-deep-dives", "HowTo"),
    ("rabbit-dental-xray-when-needed", "when your rabbit actually needs a dental x-ray", "care-deep-dives", "Article"),
    ("rabbit-tooth-root-abscess-warning", "tooth-root abscess in rabbits is not a normal lump", "care-deep-dives", "Article"),
    ("rabbit-tongue-injury-from-spurs", "how molar spurs cut the tongue, and what to watch", "care-deep-dives", "Article"),
    ("rabbit-drooling-not-always-teeth", "drooling in rabbits: dental, gi, or heat", "care-deep-dives", "Article"),
    ("rabbit-jaw-swelling-emergency", "jaw swelling in rabbits is a same-week vet trip", "care-deep-dives", "Article"),
    ("rabbit-tooth-extraction-aftercare", "post-extraction care for rabbits at home", "care-deep-dives", "HowTo"),
    ("rabbit-pellet-size-and-teeth", "pellet shape affects dental wear, here is how", "care-deep-dives", "Article"),
    ("rabbit-chew-toys-vet-approved-sg", "chew toys that actually help dental health", "product-reviews", "Article"),
    ("rabbit-dental-supplements-truth", "do dental supplements work for rabbits", "care-deep-dives", "Article"),
    ("rabbit-mouth-pain-signs-subtle", "subtle mouth pain signs most owners miss", "care-deep-dives", "Article"),
    ("rabbit-tooth-grinding-purr-vs-pain", "tooth purring vs pain grinding, the difference", "behaviour-troubleshooting", "Article"),
    ("rabbit-overgrown-incisors-photo-guide", "overgrown incisors stage-by-stage photo guide", "care-deep-dives", "Article"),
    ("rabbit-dental-diet-conversion", "switching to a dental-friendly diet without stasis", "care-deep-dives", "HowTo"),
    ("rabbit-jaw-abscess-vs-tooth", "jaw abscess vs tooth abscess in rabbits", "care-deep-dives", "Article"),
    ("rabbit-dental-cost-comparison-sg", "dental work cost comparison across SG vets", "vet-comparisons", "Article"),
    ("rabbit-dental-recheck-frequency", "how often to recheck after a dental procedure", "care-deep-dives", "Article"),

    # ============= HEALTH: GI / DIGESTIVE (30) =============
    ("rabbit-bloat-vs-gas-difference", "bloat vs gas in rabbits, very different urgencies", "care-deep-dives", "Article"),
    ("rabbit-stasis-recovery-day-by-day", "gi stasis recovery, hour by hour at home", "care-deep-dives", "HowTo"),
    ("rabbit-uneaten-cecotropes-causes", "why your rabbit stops eating cecotropes", "care-deep-dives", "Article"),
    ("rabbit-mucus-in-poop-causes", "mucus in rabbit poop, what it actually means", "care-deep-dives", "Article"),
    ("rabbit-string-of-pearls-poop", "string-of-pearls poop and what to do tonight", "care-deep-dives", "Article"),
    ("rabbit-tiny-poop-shape-meaning", "tiny rabbit poops are a warning, not a quirk", "care-deep-dives", "Article"),
    ("rabbit-no-poop-12-hours-protocol", "no poop for 12 hours, the 12-hour rabbit protocol", "care-deep-dives", "HowTo"),
    ("rabbit-soft-stool-vs-diarrhea", "soft stool vs diarrhea, why the distinction matters", "care-deep-dives", "Article"),
    ("rabbit-laxative-foods-safe-list", "laxative foods rabbits can safely eat", "care-deep-dives", "Article"),
    ("rabbit-fiber-deficiency-warning-signs", "fiber deficiency signs before stasis kicks in", "care-deep-dives", "Article"),
    ("rabbit-gut-motility-massage-howto", "safe abdominal massage for slow gut", "care-deep-dives", "HowTo"),
    ("rabbit-probiotics-actual-evidence", "do probiotics actually help rabbits", "care-deep-dives", "Article"),
    ("rabbit-meloxicam-after-stasis", "meloxicam dosing after stasis, vet-led plan", "care-deep-dives", "Article"),
    ("rabbit-ileus-vs-stasis-vocab", "ileus, stasis, bloat: vocabulary that confuses owners", "care-deep-dives", "Article"),
    ("rabbit-hairball-prevention-grooming-cadence", "grooming cadence that actually prevents hairballs", "care-deep-dives", "HowTo"),
    ("rabbit-syringe-feeding-critical-care", "syringe feeding without aspiration risk", "care-deep-dives", "HowTo"),
    ("rabbit-critical-care-brands-sg", "critical care brands available in singapore", "product-reviews", "Article"),
    ("rabbit-stasis-emergency-kit-contents", "what belongs in a rabbit stasis emergency kit", "care-deep-dives", "Article"),
    ("rabbit-belly-bloat-position", "belly position that signals dangerous bloat", "care-deep-dives", "Article"),
    ("rabbit-not-drinking-water-causes", "rabbit not drinking water, ranked by likelihood", "care-deep-dives", "Article"),
    ("rabbit-stasis-pain-management", "pain management during gi stasis, not optional", "care-deep-dives", "Article"),
    ("rabbit-overweight-stasis-risk", "why overweight rabbits get stasis faster", "care-deep-dives", "Article"),
    ("rabbit-cecal-dysbiosis-sign", "cecal dysbiosis in rabbits, the smelly poop sign", "care-deep-dives", "Article"),
    ("rabbit-poop-color-chart-singapore", "rabbit poop color chart for SG owners", "care-deep-dives", "Article"),
    ("rabbit-stool-sample-vet-how-to-collect", "how to collect a usable rabbit stool sample", "care-deep-dives", "HowTo"),
    ("rabbit-blood-in-stool-vs-urine", "blood in stool vs blood in urine, telling them apart", "care-deep-dives", "Article"),
    ("rabbit-foreign-body-ingestion-sg", "rabbit ate plastic, fabric, or hair, next steps", "care-deep-dives", "HowTo"),
    ("rabbit-stasis-after-spay-neuter", "stasis after surgery, prevention plan", "care-deep-dives", "Article"),
    ("rabbit-banana-laxative-myth", "banana as a laxative for rabbits, what is true", "care-deep-dives", "Article"),
    ("rabbit-papaya-tablets-debate", "papaya tablets for rabbits, evidence vs anecdote", "care-deep-dives", "Article"),

    # ============= HEALTH: RESPIRATORY (15) =============
    ("rabbit-snuffles-vs-cold-difference", "snuffles vs simple cold in rabbits", "care-deep-dives", "Article"),
    ("rabbit-pasteurella-sg-treatment", "pasteurella in rabbits, treatment options in SG", "care-deep-dives", "Article"),
    ("rabbit-sneezing-vs-honking", "sneezing vs honking, what each sound means", "care-deep-dives", "Article"),
    ("rabbit-nebulizer-treatment-home", "nebulizer treatment for rabbits at home", "care-deep-dives", "HowTo"),
    ("rabbit-pneumonia-warning-signs", "rabbit pneumonia signs, no time to wait", "care-deep-dives", "Article"),
    ("rabbit-runny-nose-causes-ranked", "runny nose in rabbits, ranked by cause", "care-deep-dives", "Article"),
    ("rabbit-respiratory-infection-meds", "rabbit respiratory antibiotics, what works", "care-deep-dives", "Article"),
    ("rabbit-air-quality-impact-haze-sg", "air quality impact on rabbits during haze", "care-deep-dives", "Article"),
    ("rabbit-air-purifier-recommendation-sg", "air purifier picks for rabbit households in SG", "product-reviews", "Article"),
    ("rabbit-incense-smoke-toxicity", "incense and smoke toxicity in rabbits", "care-deep-dives", "Article"),
    ("rabbit-mouth-breathing-emergency", "rabbit mouth-breathing is an emergency, period", "care-deep-dives", "Article"),
    ("rabbit-chronic-snuffles-management", "managing chronic snuffles long-term", "care-deep-dives", "Article"),
    ("rabbit-tear-duct-vs-snuffles", "tear duct issue vs upper respiratory in rabbits", "care-deep-dives", "Article"),
    ("rabbit-cough-vs-hiccups", "rabbit cough vs hiccups, telling them apart", "care-deep-dives", "Article"),
    ("rabbit-bordetella-risk-multi-pet", "bordetella risk in homes with dogs or cats", "care-deep-dives", "Article"),

    # ============= HEALTH: PARASITES / SKIN (20) =============
    ("rabbit-mites-treatment-sg", "rabbit mites treatment options in singapore", "care-deep-dives", "Article"),
    ("rabbit-fur-mites-vs-ear-mites", "fur mites vs ear mites, treatment differs", "care-deep-dives", "Article"),
    ("rabbit-revolution-selamectin-dosing", "selamectin dosing for rabbits, vet-led", "care-deep-dives", "Article"),
    ("rabbit-ringworm-treatment-protocol", "rabbit ringworm treatment that actually works", "care-deep-dives", "Article"),
    ("rabbit-bald-spots-causes-ranked", "bald spots in rabbits, ranked by cause", "care-deep-dives", "Article"),
    ("rabbit-dandruff-flaky-skin-sg", "dandruff and flaky skin in SG rabbits", "care-deep-dives", "Article"),
    ("rabbit-wet-dewlap-rash", "wet dewlap and chin rash, fixing the root cause", "care-deep-dives", "Article"),
    ("rabbit-skin-tag-vs-tumor", "skin tag vs tumor in rabbits, when to biopsy", "care-deep-dives", "Article"),
    ("rabbit-encephalitozoon-cuniculi-treatment", "e. cuniculi treatment plan and prognosis", "care-deep-dives", "Article"),
    ("rabbit-coccidia-detection-sg", "coccidia in rabbits, detection and treatment", "care-deep-dives", "Article"),
    ("rabbit-pinworms-treatment-debate", "pinworms in rabbits, treat or leave alone", "care-deep-dives", "Article"),
    ("rabbit-fleas-on-rabbits-sg", "fleas on rabbits, why selamectin and not frontline", "care-deep-dives", "Article"),
    ("rabbit-frontline-toxicity-warning", "frontline is fatal to rabbits, the real story", "care-deep-dives", "Article"),
    ("rabbit-tapeworm-multi-pet-home", "tapeworm risk for rabbits in multi-pet homes", "care-deep-dives", "Article"),
    ("rabbit-ivermectin-debate-sg", "ivermectin for rabbits, when it makes sense", "care-deep-dives", "Article"),
    ("rabbit-skin-fold-dermatitis-prevention", "skin fold dermatitis prevention in chubby rabbits", "care-deep-dives", "Article"),
    ("rabbit-scaly-ears-treatment-photos", "scaly ears in rabbits, photo treatment guide", "care-deep-dives", "Article"),
    ("rabbit-itching-no-mites-found", "rabbit keeps itching but no mites found", "care-deep-dives", "Article"),
    ("rabbit-allergy-to-bedding-sg", "rabbit allergies to specific bedding types in SG", "care-deep-dives", "Article"),
    ("rabbit-skin-cancer-vs-cyst", "skin cancer vs cyst, when biopsy is worth it", "care-deep-dives", "Article"),

    # ============= HEALTH: URINARY / REPRODUCTIVE (20) =============
    ("rabbit-bladder-sludge-management", "bladder sludge in rabbits, low-calcium diet plan", "care-deep-dives", "HowTo"),
    ("rabbit-bladder-stones-surgery-sg", "bladder stones surgery cost in singapore", "vet-comparisons", "Article"),
    ("rabbit-uti-vs-sludge", "uti vs sludge in rabbits, very different treatments", "care-deep-dives", "Article"),
    ("rabbit-red-urine-vs-blood", "red urine vs blood, mostly pigment, sometimes not", "care-deep-dives", "Article"),
    ("rabbit-uterine-adenocarcinoma-prevention", "uterine cancer prevention by age, why spay early", "care-deep-dives", "Article"),
    ("rabbit-spay-cost-by-vet-sg", "rabbit spay cost by vet in singapore", "vet-comparisons", "Article"),
    ("rabbit-neuter-cost-by-vet-sg", "rabbit neuter cost by vet in singapore", "vet-comparisons", "Article"),
    ("rabbit-spay-recovery-day-by-day", "spay recovery day by day at home", "care-deep-dives", "HowTo"),
    ("rabbit-neuter-recovery-day-by-day", "neuter recovery day by day at home", "care-deep-dives", "HowTo"),
    ("rabbit-spay-vs-neuter-different-recovery", "why spay recovery is harder than neuter", "care-deep-dives", "Article"),
    ("rabbit-testicular-cancer-elderly", "testicular cancer in unneutered seniors", "care-deep-dives", "Article"),
    ("rabbit-false-pregnancy-signs", "false pregnancy in rabbits, signs and timeline", "care-deep-dives", "Article"),
    ("rabbit-pyometra-emergency", "pyometra in unspayed rabbits is an emergency", "care-deep-dives", "Article"),
    ("rabbit-incontinence-elderly", "incontinence in elderly rabbits, management plan", "care-deep-dives", "Article"),
    ("rabbit-urine-scald-prevention", "urine scald prevention in immobile rabbits", "care-deep-dives", "HowTo"),
    ("rabbit-cone-of-shame-alternatives", "alternatives to a cone after rabbit surgery", "care-deep-dives", "Article"),
    ("rabbit-stitches-removal-timing", "when stitches come out after rabbit surgery", "care-deep-dives", "Article"),
    ("rabbit-spay-pre-op-fasting-myth", "rabbits do not fast before surgery, here is why", "care-deep-dives", "Article"),
    ("rabbit-anesthesia-risk-vs-spay-benefit", "anesthesia risk vs spay benefit, the math", "care-deep-dives", "Article"),
    ("rabbit-vaginal-discharge-vet-trip", "vaginal discharge in rabbits warrants a vet trip", "care-deep-dives", "Article"),

    # ============= HEALTH: EYE / EAR (15) =============
    ("rabbit-corneal-ulcer-emergency", "corneal ulcer in rabbits, same-day vet", "care-deep-dives", "Article"),
    ("rabbit-tear-duct-blocked-flush", "blocked tear duct flush, what the vet does", "care-deep-dives", "Article"),
    ("rabbit-eye-drops-application-howto", "applying rabbit eye drops without a fight", "care-deep-dives", "HowTo"),
    ("rabbit-cataract-vs-cloudy-eye", "cataract vs cloudy eye in rabbits", "care-deep-dives", "Article"),
    ("rabbit-eye-injury-from-cage", "eye injury from cage hardware, prevention", "care-deep-dives", "Article"),
    ("rabbit-third-eyelid-prolapse", "third eyelid prolapse, what it means", "care-deep-dives", "Article"),
    ("rabbit-ear-mites-photo-progression", "ear mites in rabbits, photo progression", "care-deep-dives", "Article"),
    ("rabbit-inner-ear-infection-head-tilt", "inner ear infection causing head tilt", "care-deep-dives", "Article"),
    ("rabbit-head-tilt-vs-stroke", "head tilt vs stroke in rabbits, telling apart", "care-deep-dives", "Article"),
    ("rabbit-ear-wax-cleaning-howto", "ear wax cleaning, what is safe at home", "care-deep-dives", "HowTo"),
    ("rabbit-deaf-rabbit-care-tips", "caring for a deaf rabbit, what changes", "care-deep-dives", "Article"),
    ("rabbit-blind-rabbit-environment", "environment changes for a blind rabbit", "care-deep-dives", "HowTo"),
    ("rabbit-glaucoma-detection-rabbits", "glaucoma in rabbits, signs and treatment", "care-deep-dives", "Article"),
    ("rabbit-eye-protrusion-emergency", "rabbit eye protrusion is an emergency", "care-deep-dives", "Article"),
    ("rabbit-cold-vs-tear-duct-discharge", "cold discharge vs tear duct discharge", "care-deep-dives", "Article"),

    # ============= HEALTH: NEURO (15) =============
    ("rabbit-seizure-first-aid", "rabbit seizure first aid at home", "care-deep-dives", "HowTo"),
    ("rabbit-stroke-recovery-sg", "stroke recovery in rabbits, what to expect", "care-deep-dives", "Article"),
    ("rabbit-floppy-rabbit-syndrome", "floppy rabbit syndrome, causes and outlook", "care-deep-dives", "Article"),
    ("rabbit-rolling-vs-vestibular", "rolling vs vestibular disease in rabbits", "care-deep-dives", "Article"),
    ("rabbit-hind-leg-weakness-causes", "hind leg weakness in rabbits, ranked causes", "care-deep-dives", "Article"),
    ("rabbit-paralysis-spinal-injury", "paralysis from spinal injury, prognosis", "care-deep-dives", "Article"),
    ("rabbit-e-cuniculi-neuro-signs", "e. cuniculi neurological signs to watch", "care-deep-dives", "Article"),
    ("rabbit-tremors-causes-ranked", "tremors in rabbits, ranked by cause", "care-deep-dives", "Article"),
    ("rabbit-circling-behavior-medical", "circling is a medical sign, not a quirk", "care-deep-dives", "Article"),
    ("rabbit-nystagmus-meaning", "nystagmus in rabbits, what it tells the vet", "care-deep-dives", "Article"),
    ("rabbit-physio-after-paralysis", "physio at home after rabbit paralysis", "care-deep-dives", "HowTo"),
    ("rabbit-mobility-aids-disabled", "mobility aids for disabled rabbits", "product-reviews", "Article"),
    ("rabbit-seizure-medication-options", "anti-seizure medication for rabbits", "care-deep-dives", "Article"),
    ("rabbit-collapse-vs-flop", "collapse vs voluntary flop, big difference", "care-deep-dives", "Article"),
    ("rabbit-neuro-rehab-cost-sg", "neuro rehab cost for rabbits in SG", "vet-comparisons", "Article"),

    # ============= HEALTH: ORTHOPEDIC (15) =============
    ("rabbit-spinal-fracture-prevention", "spinal fracture prevention in pet rabbits", "care-deep-dives", "HowTo"),
    ("rabbit-broken-leg-immediate-care", "broken leg in rabbits, immediate care steps", "care-deep-dives", "HowTo"),
    ("rabbit-arthritis-senior-management", "arthritis management in senior rabbits", "care-deep-dives", "Article"),
    ("rabbit-sore-hocks-pododermatitis", "sore hocks: prevention is everything", "care-deep-dives", "Article"),
    ("rabbit-dislocated-toe-vet", "dislocated toe in rabbits, when to vet", "care-deep-dives", "Article"),
    ("rabbit-nail-trim-too-short-bleeding", "trimmed the quick, stopping the bleeding", "care-deep-dives", "HowTo"),
    ("rabbit-grease-foot-cleaning", "grease foot cleaning, the gentle method", "care-deep-dives", "HowTo"),
    ("rabbit-splay-leg-management", "splay leg in baby rabbits, management plan", "care-deep-dives", "Article"),
    ("rabbit-x-ray-cost-sg", "rabbit x-ray cost across SG vets", "vet-comparisons", "Article"),
    ("rabbit-bone-density-diet-link", "bone density and diet in indoor rabbits", "care-deep-dives", "Article"),
    ("rabbit-hop-test-mobility-check", "the hop test, a home mobility check", "care-deep-dives", "HowTo"),
    ("rabbit-orthopedic-bed-options", "orthopedic bed options for elderly rabbits", "product-reviews", "Article"),
    ("rabbit-limping-causes-ranked", "limping in rabbits, ranked by likelihood", "care-deep-dives", "Article"),
    ("rabbit-hip-dysplasia-signs", "hip dysplasia signs in pet rabbits", "care-deep-dives", "Article"),
    ("rabbit-physio-stretching-howto", "gentle stretching for senior rabbits", "care-deep-dives", "HowTo"),

    # ============= HEALTH: CANCER / TUMORS (10) =============
    ("rabbit-thymoma-treatment-options", "thymoma in rabbits, treatment paths", "care-deep-dives", "Article"),
    ("rabbit-mammary-tumor-signs", "mammary tumor signs in unspayed rabbits", "care-deep-dives", "Article"),
    ("rabbit-lipoma-vs-tumor", "lipoma vs malignant tumor, telling apart", "care-deep-dives", "Article"),
    ("rabbit-tumor-removal-cost-sg", "tumor removal cost in SG by size", "vet-comparisons", "Article"),
    ("rabbit-chemo-debate-quality-of-life", "chemo for rabbits, quality of life math", "care-deep-dives", "Article"),
    ("rabbit-lymphoma-detection", "lymphoma in rabbits, detection signs", "care-deep-dives", "Article"),
    ("rabbit-bone-cancer-warning-signs", "bone cancer in rabbits, warning signs", "care-deep-dives", "Article"),
    ("rabbit-skin-tumor-photo-guide", "skin tumor photo guide for rabbit owners", "care-deep-dives", "Article"),
    ("rabbit-biopsy-decision-framework", "deciding whether to biopsy, a framework", "care-deep-dives", "Article"),
    ("rabbit-palliative-care-options", "palliative care options for terminal rabbits", "care-deep-dives", "Article"),

    # ============= HEALTH: INFECTIOUS DISEASE (15) =============
    ("rabbit-rhdv-vaccination-sg", "rhdv vaccination availability in singapore", "care-deep-dives", "Article"),
    ("rabbit-myxomatosis-risk-sg", "myxomatosis risk in singapore, mosquito vector", "care-deep-dives", "Article"),
    ("rabbit-treponema-rabbit-syphilis", "treponema in rabbits, the misnamed condition", "care-deep-dives", "Article"),
    ("rabbit-staph-skin-infection", "staph skin infection in rabbits", "care-deep-dives", "Article"),
    ("rabbit-pseudomonas-treatment", "pseudomonas in rabbits, treatment plan", "care-deep-dives", "Article"),
    ("rabbit-rotavirus-baby-rabbits", "rotavirus in baby rabbits, watch for it", "care-deep-dives", "Article"),
    ("rabbit-tyzzers-disease-emergency", "tyzzer disease in rabbits, the bad outcome", "care-deep-dives", "Article"),
    ("rabbit-listeria-from-greens", "listeria risk from unwashed greens", "care-deep-dives", "Article"),
    ("rabbit-clostridial-enteritis", "clostridial enteritis after antibiotics", "care-deep-dives", "Article"),
    ("rabbit-fungal-skin-infections", "fungal skin infections in humid SG", "care-deep-dives", "Article"),
    ("rabbit-vaccine-schedule-sg", "vaccine schedule for rabbits in singapore", "care-deep-dives", "Article"),
    ("rabbit-bordetella-cross-species", "bordetella cross-species risk from dogs", "care-deep-dives", "Article"),
    ("rabbit-isolation-protocol-new-arrival", "isolation protocol for a new rabbit", "care-deep-dives", "HowTo"),
    ("rabbit-disinfection-after-illness", "disinfection plan after a sick rabbit", "care-deep-dives", "HowTo"),
    ("rabbit-zoonotic-risk-to-humans", "zoonotic disease risk from pet rabbits", "care-deep-dives", "Article"),

    # ============= HEALTH: ANESTHESIA / SURGERY (15) =============
    ("rabbit-anesthesia-isoflurane-vs-sevoflurane", "isoflurane vs sevoflurane for rabbits", "care-deep-dives", "Article"),
    ("rabbit-anesthesia-blood-panel-pre-op", "the pre-op blood panel, when worth it", "care-deep-dives", "Article"),
    ("rabbit-surgery-pre-op-prep-home", "pre-op prep at home before rabbit surgery", "care-deep-dives", "HowTo"),
    ("rabbit-post-op-pain-meds", "post-op pain meds for rabbits, what to expect", "care-deep-dives", "Article"),
    ("rabbit-surgery-cone-alternatives", "surgery cone alternatives for rabbits", "product-reviews", "Article"),
    ("rabbit-ecg-pre-op-rabbits", "ecg before rabbit surgery, when needed", "care-deep-dives", "Article"),
    ("rabbit-fluid-therapy-during-surgery", "iv fluids during rabbit surgery, why critical", "care-deep-dives", "Article"),
    ("rabbit-warm-recovery-cage-setup", "warm recovery cage setup for post-op", "care-deep-dives", "HowTo"),
    ("rabbit-syringe-feeding-post-surgery", "syringe feeding after surgery, day 1 plan", "care-deep-dives", "HowTo"),
    ("rabbit-bandage-care-post-surgery", "bandage care, when to call the vet", "care-deep-dives", "HowTo"),
    ("rabbit-suture-types-rabbits", "suture types for rabbits, dissolvable vs not", "care-deep-dives", "Article"),
    ("rabbit-cherry-eye-surgery-rabbits", "cherry eye surgery in rabbits, what is involved", "care-deep-dives", "Article"),
    ("rabbit-second-opinion-when-and-how", "getting a second opinion before rabbit surgery", "care-deep-dives", "Article"),
    ("rabbit-elective-vs-emergency-surgery", "elective vs emergency surgery, prep differs", "care-deep-dives", "Article"),
    ("rabbit-surgery-pet-insurance-sg", "pet insurance for rabbit surgery in SG", "vet-comparisons", "Article"),

    # ============= NUTRITION: HAY (15) =============
    ("rabbit-second-cut-vs-third-cut-timothy", "second cut vs third cut timothy hay", "care-deep-dives", "Article"),
    ("rabbit-orchard-grass-vs-timothy", "orchard grass vs timothy for rabbits", "care-deep-dives", "Article"),
    ("rabbit-meadow-hay-feeding-tips", "meadow hay feeding for picky rabbits", "care-deep-dives", "Article"),
    ("rabbit-alfalfa-when-to-give", "alfalfa hay, when it is fine, when it is not", "care-deep-dives", "Article"),
    ("rabbit-oat-hay-vs-timothy", "oat hay vs timothy, what fits which rabbit", "care-deep-dives", "Article"),
    ("rabbit-hay-storage-humid-sg", "hay storage in humid SG without mold", "care-deep-dives", "HowTo"),
    ("rabbit-hay-mold-spotting", "spotting hay mold before your rabbit eats it", "care-deep-dives", "Article"),
    ("rabbit-hay-quantity-by-weight", "hay quantity by rabbit weight, daily targets", "care-deep-dives", "Article"),
    ("rabbit-picky-hay-eater-tricks", "tricks for picky hay eaters that actually work", "care-deep-dives", "HowTo"),
    ("rabbit-hay-bedding-vs-eating", "hay for bedding vs hay for eating, separate", "care-deep-dives", "Article"),
    ("rabbit-hay-cube-supplements", "compressed hay cubes, supplement or treat", "product-reviews", "Article"),
    ("rabbit-hay-brand-comparison-sg", "hay brand comparison available in SG", "product-reviews", "Article"),
    ("rabbit-hay-rack-types-compared", "hay rack types compared by waste reduction", "product-reviews", "Article"),
    ("rabbit-hay-stems-vs-leaves", "stems vs leaves in hay, which matters", "care-deep-dives", "Article"),
    ("rabbit-hay-dust-allergy-owners", "hay dust and human allergy management", "care-deep-dives", "Article"),

    # ============= NUTRITION: PELLETS (10) =============
    ("rabbit-pellet-vs-muesli-debate", "pellet vs muesli mix, why pellet always wins", "care-deep-dives", "Article"),
    ("rabbit-pellet-brand-comparison-sg", "pellet brand comparison available in SG", "product-reviews", "Article"),
    ("rabbit-pellet-quantity-by-weight", "pellet quantity by rabbit weight", "care-deep-dives", "Article"),
    ("rabbit-pellet-ingredients-decode", "decoding pellet ingredient lists", "care-deep-dives", "Article"),
    ("rabbit-pellet-storage-tropical", "pellet storage in tropical climate, freshness", "care-deep-dives", "HowTo"),
    ("rabbit-pellet-switching-without-stasis", "switching pellets without triggering stasis", "care-deep-dives", "HowTo"),
    ("rabbit-pellet-protein-too-high", "pellet protein too high, signs and risks", "care-deep-dives", "Article"),
    ("rabbit-pellet-free-feeding-debate", "free-feeding pellets, when it goes wrong", "care-deep-dives", "Article"),
    ("rabbit-pellet-for-seniors", "pellet choice for senior rabbits", "care-deep-dives", "Article"),
    ("rabbit-pellet-junior-vs-adult", "junior vs adult pellets, when to switch", "care-deep-dives", "Article"),

    # ============= NUTRITION: VEGETABLES (15) =============
    ("rabbit-kale-vs-bok-choy", "kale vs bok choy for SG rabbits", "care-deep-dives", "Article"),
    ("rabbit-romaine-portion-by-weight", "romaine portion sizing by rabbit weight", "care-deep-dives", "Article"),
    ("rabbit-cilantro-vs-parsley-frequency", "cilantro vs parsley feeding frequency", "care-deep-dives", "Article"),
    ("rabbit-basil-mint-thai-aromatics", "basil, mint, and Thai aromatics safe list", "care-deep-dives", "Article"),
    ("rabbit-kangkong-safe-debate", "kangkong for rabbits, the SG question", "care-deep-dives", "Article"),
    ("rabbit-asian-leafy-greens-safe-list", "asian leafy greens safe list for rabbits", "care-deep-dives", "Article"),
    ("rabbit-vegetable-rotation-plan", "vegetable rotation plan, weekly schedule", "care-deep-dives", "HowTo"),
    ("rabbit-new-vegetable-intro-method", "introducing a new vegetable, the safe method", "care-deep-dives", "HowTo"),
    ("rabbit-broccoli-gas-debate", "broccoli for rabbits, gas debate settled", "care-deep-dives", "Article"),
    ("rabbit-bell-pepper-color-difference", "bell pepper color differences for rabbits", "care-deep-dives", "Article"),
    ("rabbit-cucumber-water-content", "cucumber water content, when too much", "care-deep-dives", "Article"),
    ("rabbit-carrot-tops-vs-roots", "carrot tops vs root, the truth about carrots", "care-deep-dives", "Article"),
    ("rabbit-radish-greens-safe", "radish greens for rabbits, safe in small doses", "care-deep-dives", "Article"),
    ("rabbit-sweet-potato-leaves-sg", "sweet potato leaves availability in SG", "care-deep-dives", "Article"),
    ("rabbit-wet-leaves-after-washing", "wet leaves after washing, drying matters", "care-deep-dives", "HowTo"),

    # ============= NUTRITION: TREATS (10) =============
    ("rabbit-banana-treat-size", "banana as a treat, correct portion size", "care-deep-dives", "Article"),
    ("rabbit-apple-no-seeds", "apples for rabbits, why seeds matter", "care-deep-dives", "Article"),
    ("rabbit-dried-fruit-sugar-problem", "dried fruit and the sugar problem", "care-deep-dives", "Article"),
    ("rabbit-yogurt-drops-toxic", "yogurt drops are toxic, why owners give them", "care-deep-dives", "Article"),
    ("rabbit-store-treats-banned-list", "common store treats to skip for rabbits", "care-deep-dives", "Article"),
    ("rabbit-papaya-fresh-vs-dried", "papaya fresh vs dried for rabbits", "care-deep-dives", "Article"),
    ("rabbit-blueberry-portion-size", "blueberries for rabbits, correct portion", "care-deep-dives", "Article"),
    ("rabbit-strawberry-rare-treat", "strawberries as a rare treat, frequency", "care-deep-dives", "Article"),
    ("rabbit-rosehip-dried-treat", "dried rosehips as a treat, benefits", "care-deep-dives", "Article"),
    ("rabbit-homemade-hay-cookies", "homemade hay cookies, vet-approved recipe", "care-deep-dives", "HowTo"),

    # ============= NUTRITION: WATER (10) =============
    ("rabbit-water-bottle-mold-prevention", "water bottle mold prevention in humid SG", "care-deep-dives", "HowTo"),
    ("rabbit-tap-water-vs-filtered-sg", "tap water vs filtered for rabbits in SG", "care-deep-dives", "Article"),
    ("rabbit-water-bowl-cleaning-frequency", "water bowl cleaning frequency in tropics", "care-deep-dives", "Article"),
    ("rabbit-cold-water-vs-room-temp", "cold water vs room temp for rabbits", "care-deep-dives", "Article"),
    ("rabbit-not-drinking-after-move", "rabbit not drinking after move, common causes", "care-deep-dives", "Article"),
    ("rabbit-electrolytes-when-give", "electrolytes for rabbits, when to give", "care-deep-dives", "Article"),
    ("rabbit-water-intake-by-weight", "daily water intake by rabbit weight", "care-deep-dives", "Article"),
    ("rabbit-pedialyte-debate-vet", "pedialyte for rabbits, vet-led only", "care-deep-dives", "Article"),
    ("rabbit-flavored-water-tricks", "flavored water tricks for low drinkers", "care-deep-dives", "HowTo"),
    ("rabbit-water-bottle-vs-bowl-final", "water bottle vs bowl, the deciding factors", "care-deep-dives", "Article"),

    # ============= NUTRITION: SUPPLEMENTS (10) =============
    ("rabbit-vitamin-c-debate", "vitamin c for rabbits, why mostly unneeded", "care-deep-dives", "Article"),
    ("rabbit-calcium-supplements-careful", "calcium supplements, when they harm", "care-deep-dives", "Article"),
    ("rabbit-omega-3-fish-oil-rabbits", "omega-3 for rabbits, fish oil or flax", "care-deep-dives", "Article"),
    ("rabbit-prebiotics-vs-probiotics", "prebiotics vs probiotics, what works", "care-deep-dives", "Article"),
    ("rabbit-digestive-enzymes-evidence", "digestive enzymes for rabbits, the evidence", "care-deep-dives", "Article"),
    ("rabbit-multivitamin-skip-or-not", "rabbit multivitamins, skip or not", "care-deep-dives", "Article"),
    ("rabbit-arnica-bruising-debate", "arnica for rabbit bruising, what vets say", "care-deep-dives", "Article"),
    ("rabbit-chamomile-stress-aid", "chamomile as a stress aid, dose matters", "care-deep-dives", "Article"),
    ("rabbit-dandelion-natural-medicine", "dandelion as natural medicine, when useful", "care-deep-dives", "Article"),
    ("rabbit-herbal-supplements-warning", "herbal supplements warning list", "care-deep-dives", "Article"),

    # ============= HOUSING: CAGE (15) =============
    ("rabbit-cage-size-by-breed", "cage size minimums by rabbit breed", "care-deep-dives", "Article"),
    ("rabbit-c-and-c-cage-build-guide", "c&c cage build guide for SG hdb", "care-deep-dives", "HowTo"),
    ("rabbit-x-pen-vs-cage", "x-pen vs cage, what works in HDB", "care-deep-dives", "Article"),
    ("rabbit-free-roam-setup-hdb", "free-roam setup in an HDB flat", "care-deep-dives", "HowTo"),
    ("rabbit-two-level-cage-debate", "two-level cages, the safety question", "care-deep-dives", "Article"),
    ("rabbit-wire-bottom-cage-warning", "wire bottom cages and sore hocks", "care-deep-dives", "Article"),
    ("rabbit-cage-corner-litter-setup", "corner litter setup that actually works", "care-deep-dives", "HowTo"),
    ("rabbit-cage-cleaning-rhythm", "cage cleaning rhythm without disturbance", "care-deep-dives", "HowTo"),
    ("rabbit-cage-vs-pen-trade-offs", "cage vs pen trade-offs for HDB", "care-deep-dives", "Article"),
    ("rabbit-cage-decor-safe", "cage decor that is actually safe", "care-deep-dives", "Article"),
    ("rabbit-cage-placement-flat", "where to place the cage in an HDB flat", "care-deep-dives", "Article"),
    ("rabbit-cage-temperature-airflow", "cage placement and airflow in tropics", "care-deep-dives", "Article"),
    ("rabbit-portable-pen-travel", "portable pen for moving and travel", "product-reviews", "Article"),
    ("rabbit-cage-modifications-senior", "cage modifications for senior rabbits", "care-deep-dives", "HowTo"),
    ("rabbit-cage-multi-rabbit-shared", "cage setup for bonded pairs", "care-deep-dives", "Article"),

    # ============= HOUSING: FLOORING (10) =============
    ("rabbit-flooring-vinyl-vs-tiles", "vinyl vs tiles for rabbit rooms", "care-deep-dives", "Article"),
    ("rabbit-marble-floor-slipping", "marble floor slipping risk for rabbits", "care-deep-dives", "Article"),
    ("rabbit-flooring-non-slip-mats", "non-slip mats for rabbits, picks tested", "product-reviews", "Article"),
    ("rabbit-puzzle-mat-foam-safety", "puzzle mat foam, chewing risk", "care-deep-dives", "Article"),
    ("rabbit-fleece-blanket-flooring", "fleece blanket flooring, cleaning rhythm", "care-deep-dives", "Article"),
    ("rabbit-carpet-protection-hdb", "carpet protection in an HDB flat", "care-deep-dives", "HowTo"),
    ("rabbit-rug-rotation-cleaning", "rug rotation cleaning system", "care-deep-dives", "HowTo"),
    ("rabbit-baby-gates-flooring-divider", "baby gates as flooring zone dividers", "care-deep-dives", "Article"),
    ("rabbit-flooring-budget-options", "budget flooring options that work", "care-deep-dives", "Article"),
    ("rabbit-flooring-after-flood-leak", "rabbit-safe flooring after a flat leak", "care-deep-dives", "Article"),

    # ============= HOUSING: TEMPERATURE (10) =============
    ("rabbit-aircon-temperature-ideal", "ideal aircon temperature for rabbits", "care-deep-dives", "Article"),
    ("rabbit-cooling-tile-vs-mat", "cooling tile vs cooling mat, which wins", "product-reviews", "Article"),
    ("rabbit-frozen-bottle-hack", "frozen bottle hack, safer than ice", "care-deep-dives", "HowTo"),
    ("rabbit-aircon-bill-savings-tips", "aircon bill savings without harming rabbit", "care-deep-dives", "Article"),
    ("rabbit-temperature-monitor-alarm", "temperature monitor with alarm, picks", "product-reviews", "Article"),
    ("rabbit-fan-direction-airflow", "fan direction and airflow, do not point", "care-deep-dives", "Article"),
    ("rabbit-emergency-cooling-power-out", "emergency cooling when power is out", "care-deep-dives", "HowTo"),
    ("rabbit-humidity-management-tropics", "humidity management for SG rabbit rooms", "care-deep-dives", "Article"),
    ("rabbit-dehumidifier-rabbit-safe", "dehumidifier picks safe for rabbits", "product-reviews", "Article"),
    ("rabbit-heat-stroke-recovery", "heat stroke recovery, the next 24 hours", "care-deep-dives", "HowTo"),

    # ============= HOUSING: ENRICHMENT (15) =============
    ("rabbit-toy-rotation-schedule", "toy rotation schedule for a bored rabbit", "care-deep-dives", "HowTo"),
    ("rabbit-cardboard-castles-build", "cardboard castles a rabbit will actually use", "care-deep-dives", "HowTo"),
    ("rabbit-paper-bag-enrichment", "paper bag enrichment, safest paper types", "care-deep-dives", "Article"),
    ("rabbit-foraging-toy-diy-sg", "foraging toy diy with SG materials", "care-deep-dives", "HowTo"),
    ("rabbit-snuffle-mat-too-easy", "snuffle mat too easy, leveling it up", "care-deep-dives", "Article"),
    ("rabbit-tunnel-toys-compared", "tunnel toys compared for adult rabbits", "product-reviews", "Article"),
    ("rabbit-digging-box-build", "digging box build that survives a month", "care-deep-dives", "HowTo"),
    ("rabbit-untreated-wood-list", "untreated wood safe for chewing", "care-deep-dives", "Article"),
    ("rabbit-willow-balls-where-buy-sg", "willow balls, where to buy in singapore", "product-reviews", "Article"),
    ("rabbit-grass-mat-vs-seagrass", "grass mat vs seagrass for chewing", "care-deep-dives", "Article"),
    ("rabbit-clicker-training-rabbits", "clicker training rabbits, possible in a month", "care-deep-dives", "HowTo"),
    ("rabbit-tricks-spin-up-shake", "tricks like spin, up, shake, taught calmly", "care-deep-dives", "HowTo"),
    ("rabbit-target-stick-training", "target stick training basics", "care-deep-dives", "HowTo"),
    ("rabbit-puzzle-feeders-tested", "puzzle feeders tested with real rabbits", "product-reviews", "Article"),
    ("rabbit-music-tv-background-effects", "music and tv background effects on rabbits", "care-deep-dives", "Article"),

    # ============= BEHAVIOR: AGGRESSION (10) =============
    ("rabbit-biting-during-cleaning", "biting during cage cleaning, fixing it", "behaviour-troubleshooting", "Article"),
    ("rabbit-territorial-after-spay", "territorial behavior after spay, timeline", "behaviour-troubleshooting", "Article"),
    ("rabbit-hormonal-aggression-stages", "hormonal aggression stages by age", "behaviour-troubleshooting", "Article"),
    ("rabbit-fighting-bonded-pair-broke", "bonded pair broke up, recovery options", "behaviour-troubleshooting", "Article"),
    ("rabbit-attacking-feet-fix", "rabbit attacking feet, fixing it without punishment", "behaviour-troubleshooting", "HowTo"),
    ("rabbit-charging-new-rabbit", "charging a new rabbit during intro", "behaviour-troubleshooting", "Article"),
    ("rabbit-growling-at-vacuum", "growling at the vacuum, desensitization", "behaviour-troubleshooting", "HowTo"),
    ("rabbit-resource-guarding-food", "resource guarding food, fixing it", "behaviour-troubleshooting", "Article"),
    ("rabbit-cage-aggression-reasons", "cage aggression reasons, ranked", "behaviour-troubleshooting", "Article"),
    ("rabbit-redirecting-bite-energy", "redirecting bite energy to safe targets", "behaviour-troubleshooting", "HowTo"),

    # ============= BEHAVIOR: FEAR (10) =============
    ("rabbit-flinching-at-hands-trauma", "flinching at hands, trauma-informed approach", "behaviour-troubleshooting", "Article"),
    ("rabbit-hiding-all-day-causes", "hiding all day, ranked causes", "behaviour-troubleshooting", "Article"),
    ("rabbit-thunder-fear-protocol", "thunder fear protocol for SG rabbits", "behaviour-troubleshooting", "HowTo"),
    ("rabbit-stranger-fear-visitors", "stranger fear with visitors, slow intro", "behaviour-troubleshooting", "Article"),
    ("rabbit-fear-of-being-picked-up", "fear of being picked up, gentle re-training", "behaviour-troubleshooting", "HowTo"),
    ("rabbit-shaking-when-scared", "shaking when scared, when to worry", "behaviour-troubleshooting", "Article"),
    ("rabbit-freeze-response-vs-collapse", "freeze response vs collapse, telling apart", "behaviour-troubleshooting", "Article"),
    ("rabbit-fear-of-car-rides", "fear of car rides, building tolerance", "behaviour-troubleshooting", "HowTo"),
    ("rabbit-pheromone-products-evidence", "rabbit pheromone products, evidence for SG", "product-reviews", "Article"),
    ("rabbit-noise-desensitization-plan", "noise desensitization plan for HDB", "behaviour-troubleshooting", "HowTo"),

    # ============= BEHAVIOR: AFFECTION (10) =============
    ("rabbit-tooth-purring-meaning", "tooth purring, what it actually means", "behaviour-troubleshooting", "Article"),
    ("rabbit-licking-vs-grooming-you", "licking vs grooming you, the difference", "behaviour-troubleshooting", "Article"),
    ("rabbit-nudging-you-want", "nudging you, the four common wants", "behaviour-troubleshooting", "Article"),
    ("rabbit-circling-you-hormonal", "circling you, the hormonal sign", "behaviour-troubleshooting", "Article"),
    ("rabbit-loafing-near-you-meaning", "loafing near you, trust signal explained", "behaviour-troubleshooting", "Article"),
    ("rabbit-flopping-next-to-you", "flopping next to you, the bond marker", "behaviour-troubleshooting", "Article"),
    ("rabbit-following-you-room-to-room", "following you room to room, what it signals", "behaviour-troubleshooting", "Article"),
    ("rabbit-honking-vs-snorting", "honking vs snorting, telling apart", "behaviour-troubleshooting", "Article"),
    ("rabbit-sleeping-with-eyes-open", "sleeping with eyes open, when normal", "behaviour-troubleshooting", "Article"),
    ("rabbit-chin-marking-territory", "chin marking, what they are claiming", "behaviour-troubleshooting", "Article"),

    # ============= BEHAVIOR: COMMUNICATION (10) =============
    ("rabbit-thumping-causes-ranked", "thumping causes, ranked by frequency", "behaviour-troubleshooting", "Article"),
    ("rabbit-soft-grunt-meaning", "soft grunt vs aggressive grunt", "behaviour-troubleshooting", "Article"),
    ("rabbit-purr-vs-pain-grind", "purr vs pain grind, the sound difference", "behaviour-troubleshooting", "Article"),
    ("rabbit-vocalizations-decode", "decoding rabbit vocalizations, full chart", "behaviour-troubleshooting", "Article"),
    ("rabbit-ear-positions-decode", "decoding ear positions, full chart", "behaviour-troubleshooting", "Article"),
    ("rabbit-tail-positions-meaning", "tail positions and what they mean", "behaviour-troubleshooting", "Article"),
    ("rabbit-body-language-photo-chart", "rabbit body language photo chart", "behaviour-troubleshooting", "Article"),
    ("rabbit-eye-position-stress-signal", "eye position as a stress signal", "behaviour-troubleshooting", "Article"),
    ("rabbit-quiet-mouth-twitch", "quiet mouth twitch when content", "behaviour-troubleshooting", "Article"),
    ("rabbit-binky-vs-twist", "binky vs twist, the joy spectrum", "behaviour-troubleshooting", "Article"),

    # ============= BEHAVIOR: LITTER TRAINING (10) =============
    ("rabbit-litter-regression-after-move", "litter regression after a move, fix plan", "behaviour-troubleshooting", "Article"),
    ("rabbit-spot-cleaning-rhythm", "spot cleaning rhythm for litter trays", "care-deep-dives", "HowTo"),
    ("rabbit-pee-spray-fixing", "pee spraying, hormonal vs habit", "behaviour-troubleshooting", "Article"),
    ("rabbit-poop-outside-litter-causes", "poop outside the litter, ranked causes", "behaviour-troubleshooting", "Article"),
    ("rabbit-paper-pellets-vs-aspen", "paper pellets vs aspen for litter", "product-reviews", "Article"),
    ("rabbit-litter-near-hay-rack", "litter near hay rack, why it works", "care-deep-dives", "Article"),
    ("rabbit-multiple-litter-boxes-when", "multiple litter boxes, when needed", "care-deep-dives", "Article"),
    ("rabbit-litter-tray-size-by-breed", "litter tray size by rabbit breed", "care-deep-dives", "Article"),
    ("rabbit-pee-volume-suddenly-large", "pee volume suddenly large, when to worry", "care-deep-dives", "Article"),
    ("rabbit-litter-deep-clean-rhythm", "deep clean rhythm for litter boxes", "care-deep-dives", "HowTo"),

    # ============= BEHAVIOR: BINKIES / ZOOMIES (10) =============
    ("rabbit-zoomies-time-of-day", "zoomies time of day, what is crepuscular", "behaviour-troubleshooting", "Article"),
    ("rabbit-binky-different-types", "binky types, full body vs head", "behaviour-troubleshooting", "Article"),
    ("rabbit-too-much-energy-fix", "too much energy, channeling productively", "behaviour-troubleshooting", "HowTo"),
    ("rabbit-low-energy-vs-sad", "low energy vs sad, sickness or mood", "behaviour-troubleshooting", "Article"),
    ("rabbit-zoomies-cage-too-small", "zoomies as a cage too small sign", "behaviour-troubleshooting", "Article"),
    ("rabbit-jumping-on-couch-injury", "jumping on couch and back injury risk", "care-deep-dives", "Article"),
    ("rabbit-exercise-time-per-day", "exercise time per day by age", "care-deep-dives", "Article"),
    ("rabbit-rabbit-yoga-stretching", "rabbit yoga stretching, real behavior", "behaviour-troubleshooting", "Article"),
    ("rabbit-overstimulated-end-zoomies", "ending zoomies before overstimulation", "behaviour-troubleshooting", "HowTo"),
    ("rabbit-binky-trigger-conditions", "binky trigger conditions for a happy rabbit", "behaviour-troubleshooting", "Article"),

    # ============= BONDING: MULTI RABBIT (15) =============
    ("rabbit-bonding-timeline-realistic", "realistic bonding timeline week by week", "care-deep-dives", "Article"),
    ("rabbit-neutral-territory-method", "neutral territory method, step by step", "care-deep-dives", "HowTo"),
    ("rabbit-stress-bonding-debate-sg", "stress bonding debate, what SG owners do", "care-deep-dives", "Article"),
    ("rabbit-pre-bonding-prep-vet", "pre-bonding vet prep, what is needed", "care-deep-dives", "Article"),
    ("rabbit-bond-broken-after-vet", "bond broken after a vet trip, recovery", "care-deep-dives", "Article"),
    ("rabbit-trio-bonding-feasibility", "trio bonding feasibility, the math", "care-deep-dives", "Article"),
    ("rabbit-failed-bond-signs-stop", "failed bond signs, when to stop trying", "care-deep-dives", "Article"),
    ("rabbit-bonded-pair-grief-loss", "bonded pair grief, supporting the survivor", "care-deep-dives", "Article"),
    ("rabbit-litter-share-pre-bonding", "shared litter pre-bonding, does it help", "care-deep-dives", "Article"),
    ("rabbit-bonding-male-female-pairing", "male-female pairing odds, the data", "care-deep-dives", "Article"),
    ("rabbit-bonding-same-sex-pairs", "same-sex pairs, when they work", "care-deep-dives", "Article"),
    ("rabbit-age-gap-bonding-impact", "age gap impact on bonding success", "care-deep-dives", "Article"),
    ("rabbit-personality-match-bonding", "personality match for bonding success", "care-deep-dives", "Article"),
    ("rabbit-introduction-photo-progression", "introduction photo progression at home", "care-deep-dives", "Article"),
    ("rabbit-bonding-with-rescue-rabbit", "bonding with a rescue rabbit, expectations", "care-deep-dives", "Article"),

    # ============= BONDING: OTHER PETS (10) =============
    ("rabbit-cat-coexist-rules", "rabbit and cat coexistence rules", "care-deep-dives", "Article"),
    ("rabbit-dog-introduction-step-by-step", "dog introduction step by step", "care-deep-dives", "HowTo"),
    ("rabbit-with-hamsters-rodent-risk", "rabbits and hamsters, rodent disease risk", "care-deep-dives", "Article"),
    ("rabbit-with-guinea-pig-housing", "rabbit and guinea pig housing separately", "care-deep-dives", "Article"),
    ("rabbit-with-children-rules", "rabbits and children, household rules", "care-deep-dives", "Article"),
    ("rabbit-with-fish-tank-safety", "rabbits and fish tank safety", "care-deep-dives", "Article"),
    ("rabbit-with-bird-cage", "rabbits and caged birds, separation", "care-deep-dives", "Article"),
    ("rabbit-with-cat-litter-toxicity", "rabbit access to cat litter, toxicity", "care-deep-dives", "Article"),
    ("rabbit-meeting-strangers-pet", "meeting other strangers' pets, risks", "care-deep-dives", "Article"),
    ("rabbit-shared-space-rules-multi-species", "shared space rules in multi-species home", "care-deep-dives", "HowTo"),

    # ============= BONDING: HUMAN (10) =============
    ("rabbit-first-week-bonding-routine", "first week bonding routine with your rabbit", "care-deep-dives", "HowTo"),
    ("rabbit-trust-building-week-by-week", "trust building week by week plan", "care-deep-dives", "HowTo"),
    ("rabbit-floor-time-vs-lap-time", "floor time vs lap time, what rabbits prefer", "care-deep-dives", "Article"),
    ("rabbit-petting-zones-prefer", "petting zones rabbits prefer, photo guide", "care-deep-dives", "Article"),
    ("rabbit-bonding-with-shy-rabbit", "bonding with a shy rabbit, slow approach", "care-deep-dives", "HowTo"),
    ("rabbit-recall-training-treat", "recall training with a treat", "care-deep-dives", "HowTo"),
    ("rabbit-trust-after-trauma-vet", "rebuilding trust after a traumatic vet trip", "care-deep-dives", "Article"),
    ("rabbit-second-rabbit-jealousy", "second rabbit and human jealousy", "care-deep-dives", "Article"),
    ("rabbit-bonding-with-new-housemate", "bonding with a new housemate or partner", "care-deep-dives", "HowTo"),
    ("rabbit-children-supervised-bonding", "children supervised bonding, what to teach", "care-deep-dives", "Article"),

    # ============= BREED DEEPDIVES (30) =============
    ("rabbit-french-lop-care-sg", "french lop care in singapore", "breed-specific-sg", "Article"),
    ("rabbit-english-lop-ears-care", "english lop ears, care challenges", "breed-specific-sg", "Article"),
    ("rabbit-jersey-wooly-grooming", "jersey wooly grooming for SG humidity", "breed-specific-sg", "Article"),
    ("rabbit-angora-trim-vs-shave", "angora trim vs shave for SG climate", "breed-specific-sg", "Article"),
    ("rabbit-flemish-giant-care-sg", "flemish giant care, hdb size limits", "breed-specific-sg", "Article"),
    ("rabbit-checkered-giant-temperament", "checkered giant temperament, the active breed", "breed-specific-sg", "Article"),
    ("rabbit-dutch-rabbit-personality", "dutch rabbit personality and care", "breed-specific-sg", "Article"),
    ("rabbit-himalayan-temperature-link", "himalayan rabbit color and temperature", "breed-specific-sg", "Article"),
    ("rabbit-californian-vs-himalayan", "californian vs himalayan, telling apart", "breed-specific-sg", "Article"),
    ("rabbit-new-zealand-white-care", "new zealand white care basics", "breed-specific-sg", "Article"),
    ("rabbit-tan-rabbit-personality", "tan rabbit personality, the lively breed", "breed-specific-sg", "Article"),
    ("rabbit-fuzzy-lop-grooming", "fuzzy lop grooming needs", "breed-specific-sg", "Article"),
    ("rabbit-mini-satin-rare-sg", "mini satin, rare in SG, finding one", "breed-specific-sg", "Article"),
    ("rabbit-britannia-petite-energy", "britannia petite energy, not for everyone", "breed-specific-sg", "Article"),
    ("rabbit-polish-rabbit-care", "polish rabbit care, smallest breed", "breed-specific-sg", "Article"),
    ("rabbit-mixed-breed-care-tips", "mixed breed rabbit care tips", "breed-specific-sg", "Article"),
    ("rabbit-continental-giant-sg", "continental giant in SG, feasibility", "breed-specific-sg", "Article"),
    ("rabbit-rhinelander-spotting", "rhinelander markings and rarity", "breed-specific-sg", "Article"),
    ("rabbit-american-fuzzy-lop-grooming", "american fuzzy lop grooming routine", "breed-specific-sg", "Article"),
    ("rabbit-silver-fox-care-rare", "silver fox rabbit, very rare in SG", "breed-specific-sg", "Article"),
    ("rabbit-harlequin-color-genetics", "harlequin color genetics, simple version", "breed-specific-sg", "Article"),
    ("rabbit-mini-lop-vs-american-mini", "mini lop vs american mini lop, the difference", "breed-specific-sg", "Article"),
    ("rabbit-dwarf-hotot-eye-care", "dwarf hotot eye care, the breed quirk", "breed-specific-sg", "Article"),
    ("rabbit-cinnamon-rabbit-color", "cinnamon rabbit color, recognizing it", "breed-specific-sg", "Article"),
    ("rabbit-rex-velveteen-coat-care", "rex velveteen coat, special grooming", "breed-specific-sg", "Article"),
    ("rabbit-mini-rex-color-varieties", "mini rex color varieties available in SG", "breed-specific-sg", "Article"),
    ("rabbit-broken-pattern-color", "broken pattern color in rabbits", "breed-specific-sg", "Article"),
    ("rabbit-otter-pattern-recognizing", "otter pattern recognizing in rabbits", "breed-specific-sg", "Article"),
    ("rabbit-marten-coat-color", "marten coat color in rabbits", "breed-specific-sg", "Article"),
    ("rabbit-self-color-vs-agouti", "self color vs agouti pattern, telling apart", "breed-specific-sg", "Article"),

    # ============= LIFE STAGE: BABY (10) =============
    ("rabbit-baby-weight-gain-chart", "baby rabbit weight gain chart week by week", "care-deep-dives", "Article"),
    ("rabbit-kit-feeding-orphan", "feeding orphan kits, the survival protocol", "care-deep-dives", "HowTo"),
    ("rabbit-when-to-wean-kit", "when to wean a kit, the timing", "care-deep-dives", "Article"),
    ("rabbit-baby-illness-warning-signs", "baby illness warning signs, fast deterioration", "care-deep-dives", "Article"),
    ("rabbit-baby-bunny-bites-soft", "baby bunny bites, soft mouthing", "behaviour-troubleshooting", "Article"),
    ("rabbit-baby-litter-train-when", "when to start litter training a baby", "care-deep-dives", "Article"),
    ("rabbit-baby-pellet-introduction", "pellet introduction for baby rabbits", "care-deep-dives", "Article"),
    ("rabbit-baby-vegetable-intro-age", "vegetable introduction age for kits", "care-deep-dives", "Article"),
    ("rabbit-baby-cage-vs-adult", "baby cage vs adult cage, what changes", "care-deep-dives", "Article"),
    ("rabbit-baby-handling-window-bonding", "baby handling window for bonding", "care-deep-dives", "Article"),

    # ============= LIFE STAGE: JUVENILE (5) =============
    ("rabbit-teenage-rabbit-behavior", "teenage rabbit behavior, the rough months", "behaviour-troubleshooting", "Article"),
    ("rabbit-hormones-onset-by-breed", "hormone onset by breed, knowing timing", "care-deep-dives", "Article"),
    ("rabbit-pre-spay-pre-neuter-prep", "pre-spay and pre-neuter prep at home", "care-deep-dives", "HowTo"),
    ("rabbit-adolescent-aggression-temporary", "adolescent aggression, mostly temporary", "behaviour-troubleshooting", "Article"),
    ("rabbit-juvenile-diet-transition", "juvenile diet transition by month", "care-deep-dives", "Article"),

    # ============= LIFE STAGE: ADULT (5) =============
    ("rabbit-adult-rabbit-weight-management", "adult rabbit weight management plan", "care-deep-dives", "HowTo"),
    ("rabbit-annual-checkup-what-vet-checks", "annual checkup, what the vet checks", "care-deep-dives", "Article"),
    ("rabbit-adult-rabbit-routine-tracking", "adult routine tracking app or journal", "care-deep-dives", "Article"),
    ("rabbit-mid-life-baseline-bloodwork", "mid-life baseline bloodwork, what for", "care-deep-dives", "Article"),
    ("rabbit-adult-diet-fine-tune", "fine-tuning the adult rabbit diet", "care-deep-dives", "Article"),

    # ============= LIFE STAGE: SENIOR (15) =============
    ("rabbit-senior-rabbit-age-cutoff", "when is a rabbit considered senior", "care-deep-dives", "Article"),
    ("rabbit-senior-cage-adjustments", "senior cage adjustments for arthritis", "care-deep-dives", "HowTo"),
    ("rabbit-senior-litter-mobility-fix", "senior litter mobility fixes", "care-deep-dives", "HowTo"),
    ("rabbit-senior-diet-changes-needed", "senior diet changes needed", "care-deep-dives", "Article"),
    ("rabbit-senior-bloodwork-frequency", "senior bloodwork frequency", "care-deep-dives", "Article"),
    ("rabbit-senior-arthritis-meds", "arthritis meds for senior rabbits", "care-deep-dives", "Article"),
    ("rabbit-senior-cataract-management", "cataract management in old rabbits", "care-deep-dives", "Article"),
    ("rabbit-senior-dental-monitoring", "dental monitoring for elderly rabbits", "care-deep-dives", "Article"),
    ("rabbit-senior-hydration-tracking", "hydration tracking for elderly rabbits", "care-deep-dives", "HowTo"),
    ("rabbit-senior-grooming-help", "grooming help for senior rabbits", "care-deep-dives", "HowTo"),
    ("rabbit-senior-handling-fragile", "handling a fragile senior rabbit", "care-deep-dives", "Article"),
    ("rabbit-senior-bonding-with-younger", "senior bonding with a younger rabbit", "care-deep-dives", "Article"),
    ("rabbit-senior-stairs-ramps", "stairs and ramps for senior rabbits", "care-deep-dives", "HowTo"),
    ("rabbit-senior-vision-loss-environment", "vision loss and environment changes", "care-deep-dives", "HowTo"),
    ("rabbit-senior-night-routine", "night routine for elderly rabbits", "care-deep-dives", "Article"),

    # ============= LIFE STAGE: END OF LIFE (10) =============
    ("rabbit-quality-of-life-checklist", "quality of life checklist, weekly score", "care-deep-dives", "Article"),
    ("rabbit-when-to-euthanize-framework", "when to consider euthanasia, framework", "care-deep-dives", "Article"),
    ("rabbit-home-vs-vet-euthanasia-sg", "home vs vet euthanasia in singapore", "vet-comparisons", "Article"),
    ("rabbit-grief-after-loss-resources", "grief after loss, SG resources", "care-deep-dives", "Article"),
    ("rabbit-burial-cremation-options-sg", "burial vs cremation options in SG", "care-deep-dives", "Article"),
    ("rabbit-pet-cremation-services-sg", "pet cremation services in singapore", "vet-comparisons", "Article"),
    ("rabbit-keepsake-options-after-loss", "keepsake options after a rabbit passes", "care-deep-dives", "Article"),
    ("rabbit-other-rabbit-grief-bonded", "the other rabbit's grief after bonded loss", "care-deep-dives", "Article"),
    ("rabbit-when-to-get-another-rabbit", "when to get another rabbit, no rush", "care-deep-dives", "Article"),
    ("rabbit-end-stage-comfort-care", "end stage comfort care at home", "care-deep-dives", "HowTo"),

    # ============= TRAVEL / TRANSPORT (15) =============
    ("rabbit-grab-driver-rabbit-policy", "Grab drivers' rabbit policy, what works", "care-deep-dives", "Article"),
    ("rabbit-comfortdelgro-rabbit-allowed", "ComfortDelGro rabbit policy in singapore", "care-deep-dives", "Article"),
    ("rabbit-mrt-rabbit-policy", "MRT rabbit transport policy in SG", "care-deep-dives", "Article"),
    ("rabbit-bus-rabbit-allowed", "bus rabbit policy in singapore", "care-deep-dives", "Article"),
    ("rabbit-carrier-checklist-vet-trip", "carrier checklist for a vet trip", "care-deep-dives", "HowTo"),
    ("rabbit-traveling-with-medication", "traveling with rabbit medication", "care-deep-dives", "Article"),
    ("rabbit-overseas-flight-process-sg", "overseas flight process from singapore", "care-deep-dives", "HowTo"),
    ("rabbit-export-permit-sg-process", "rabbit export permit process from SG", "care-deep-dives", "Article"),
    ("rabbit-quarantine-overseas-arrival", "quarantine on overseas arrival", "care-deep-dives", "Article"),
    ("rabbit-pet-relocation-services-sg", "pet relocation services in singapore", "vet-comparisons", "Article"),
    ("rabbit-overnight-trip-planning", "overnight trip planning with a rabbit", "care-deep-dives", "HowTo"),
    ("rabbit-day-trip-out-rules", "day trips out, what rabbits can handle", "care-deep-dives", "Article"),
    ("rabbit-boarding-vs-pet-sitter", "boarding vs pet sitter, trade-offs in SG", "care-deep-dives", "Article"),
    ("rabbit-house-sitter-instructions-template", "house sitter instructions template", "care-deep-dives", "Article"),
    ("rabbit-emergency-evacuation-plan", "emergency evacuation plan in HDB", "care-deep-dives", "HowTo"),

    # ============= SG LOCATIONS (20) =============
    ("rabbit-vets-east-coast-sg", "rabbit vets in the east of singapore", "vet-comparisons", "Article"),
    ("rabbit-vets-west-sg", "rabbit vets in the west of singapore", "vet-comparisons", "Article"),
    ("rabbit-vets-north-sg", "rabbit vets in the north of singapore", "vet-comparisons", "Article"),
    ("rabbit-vets-central-sg", "rabbit vets in central singapore", "vet-comparisons", "Article"),
    ("rabbit-vets-jurong-sg", "rabbit vets in jurong, what is open", "vet-comparisons", "Article"),
    ("rabbit-vets-tampines-sg", "rabbit vets in tampines, the options", "vet-comparisons", "Article"),
    ("rabbit-vets-yishun-sg", "rabbit vets in yishun, who treats exotics", "vet-comparisons", "Article"),
    ("rabbit-vets-bedok-sg", "rabbit vets in bedok, options today", "vet-comparisons", "Article"),
    ("rabbit-vets-bukit-timah-sg", "rabbit vets in bukit timah area", "vet-comparisons", "Article"),
    ("rabbit-vets-toa-payoh-sg", "rabbit vets in toa payoh, who is open", "vet-comparisons", "Article"),
    ("rabbit-vets-clementi-sg", "rabbit vets in clementi area", "vet-comparisons", "Article"),
    ("rabbit-vets-after-hours-emergency-sg", "after-hours emergency rabbit vets in SG", "vet-comparisons", "Article"),
    ("rabbit-shops-east-coast-sg", "rabbit shops in the east of singapore", "product-reviews", "Article"),
    ("rabbit-shops-west-sg", "rabbit shops in the west of singapore", "product-reviews", "Article"),
    ("rabbit-shops-north-sg", "rabbit shops in the north of singapore", "product-reviews", "Article"),
    ("rabbit-hay-pickup-locations-sg", "hay pickup locations across singapore", "product-reviews", "Article"),
    ("rabbit-pellet-pickup-locations-sg", "pellet pickup locations across singapore", "product-reviews", "Article"),
    ("rabbit-grooming-services-sg", "rabbit grooming services in singapore", "vet-comparisons", "Article"),
    ("rabbit-nail-trim-services-sg", "rabbit nail trim services across SG", "vet-comparisons", "Article"),
    ("rabbit-sg-rabbit-meetups", "rabbit meetups in singapore, where to find", "care-deep-dives", "Article"),

    # ============= SG FESTIVALS (10) =============
    ("rabbit-deepavali-rabbit-safety", "deepavali safety for rabbits in SG", "seasonal-sg", "Article"),
    ("rabbit-hari-raya-rabbit-care", "hari raya care for rabbits", "seasonal-sg", "Article"),
    ("rabbit-christmas-rabbit-safety", "christmas decorations and rabbit safety", "seasonal-sg", "Article"),
    ("rabbit-nye-fireworks-sg-protocol", "new year fireworks protocol for rabbits", "seasonal-sg", "Article"),
    ("rabbit-mooncake-festival-lantern-safety", "mooncake festival lantern safety", "seasonal-sg", "Article"),
    ("rabbit-vesak-day-rabbit-care", "vesak day rabbit care reminders", "seasonal-sg", "Article"),
    ("rabbit-cny-reunion-dinner-rabbit", "cny reunion dinner with rabbits home", "seasonal-sg", "Article"),
    ("rabbit-cny-firecrackers-anxiety", "cny firecrackers and rabbit anxiety", "seasonal-sg", "Article"),
    ("rabbit-cny-mandarin-orange-safety", "mandarin oranges, safe in moderation", "seasonal-sg", "Article"),
    ("rabbit-cny-bak-kwa-toxicity", "bak kwa is toxic to rabbits", "seasonal-sg", "Article"),

    # ============= SG WEATHER (10) =============
    ("rabbit-haze-psi-cutoff-aircon", "haze psi cutoff for switching to aircon", "seasonal-sg", "Article"),
    ("rabbit-monsoon-leak-prep-hdb", "monsoon leak prep for HDB rabbit owners", "seasonal-sg", "Article"),
    ("rabbit-thunderstorm-protocol-sg", "thunderstorm protocol for rabbits in SG", "seasonal-sg", "Article"),
    ("rabbit-heat-wave-protocol-sg", "heat wave protocol for SG rabbits", "seasonal-sg", "Article"),
    ("rabbit-power-outage-protocol", "power outage protocol with rabbits in flat", "seasonal-sg", "Article"),
    ("rabbit-typhoon-tail-end-prep", "typhoon tail end prep, when SG gets hit", "seasonal-sg", "Article"),
    ("rabbit-air-quality-app-recommended", "air quality app picks for rabbit owners", "seasonal-sg", "Article"),
    ("rabbit-monsoon-mold-prevention", "mold prevention during the monsoon", "seasonal-sg", "Article"),
    ("rabbit-haze-mask-not-needed", "haze masks for rabbits, not the answer", "seasonal-sg", "Article"),
    ("rabbit-rainy-season-mood", "rainy season mood, what to watch", "seasonal-sg", "Article"),

    # ============= SG REGULATIONS (10) =============
    ("rabbit-hdb-rabbit-allowed-yes", "are rabbits allowed in HDB flats, yes", "care-deep-dives", "Article"),
    ("rabbit-condo-rules-rabbit-pets", "condo rules about rabbit pets", "care-deep-dives", "Article"),
    ("rabbit-avs-licensing-rabbit-sg", "AVS licensing for rabbits in singapore", "care-deep-dives", "Article"),
    ("rabbit-import-regulations-overseas", "rabbit import regulations from overseas", "care-deep-dives", "Article"),
    ("rabbit-export-regulations-sg", "rabbit export regulations from SG", "care-deep-dives", "Article"),
    ("rabbit-neighbor-complaint-noise-smell", "neighbor complaint about noise or smell", "care-deep-dives", "Article"),
    ("rabbit-renting-with-rabbit-rules", "renting with a rabbit, landlord rules", "care-deep-dives", "Article"),
    ("rabbit-condo-pet-restrictions", "common condo pet restrictions in SG", "care-deep-dives", "Article"),
    ("rabbit-multi-cat-multi-rabbit-rules", "multi-pet rules in HDB and condo", "care-deep-dives", "Article"),
    ("rabbit-license-renewal-rabbit-pet", "is there a license renewal for rabbit pet", "care-deep-dives", "Article"),

    # ============= EMERGENCY SCENARIOS (20) =============
    ("rabbit-emergency-night-clinic-sg", "emergency night clinic options in SG", "vet-comparisons", "Article"),
    ("rabbit-emergency-bag-pack-checklist", "emergency bag pack checklist for rabbits", "care-deep-dives", "HowTo"),
    ("rabbit-fall-injury-first-aid", "fall injury first aid before vet", "care-deep-dives", "HowTo"),
    ("rabbit-poisoning-first-response", "poisoning first response at home", "care-deep-dives", "HowTo"),
    ("rabbit-choking-first-aid", "choking first aid for rabbits", "care-deep-dives", "HowTo"),
    ("rabbit-bleeding-first-aid-pressure", "bleeding first aid, pressure points", "care-deep-dives", "HowTo"),
    ("rabbit-shock-recognizing-treating", "shock, recognizing and treating", "care-deep-dives", "HowTo"),
    ("rabbit-bite-from-other-pet-care", "bite from another pet, immediate care", "care-deep-dives", "HowTo"),
    ("rabbit-burn-scald-first-aid", "burn or scald first aid for rabbits", "care-deep-dives", "HowTo"),
    ("rabbit-eye-injury-flush-protocol", "eye injury flush protocol at home", "care-deep-dives", "HowTo"),
    ("rabbit-ear-flap-tear-care", "ear flap tear care before vet", "care-deep-dives", "HowTo"),
    ("rabbit-nail-broken-bleeding", "broken nail bleeding stop", "care-deep-dives", "HowTo"),
    ("rabbit-overheating-emergency-cool", "overheating emergency cooling protocol", "care-deep-dives", "HowTo"),
    ("rabbit-cold-shock-warming-protocol", "cold shock warming protocol for rabbits", "care-deep-dives", "HowTo"),
    ("rabbit-allergic-reaction-recognize", "allergic reaction, recognizing it", "care-deep-dives", "Article"),
    ("rabbit-anaphylaxis-rare-recognize", "anaphylaxis is rare, signs to know", "care-deep-dives", "Article"),
    ("rabbit-electrical-burn-after-chew", "electrical burn after chewing a cord", "care-deep-dives", "HowTo"),
    ("rabbit-foreign-object-stuck-eye", "foreign object stuck in eye", "care-deep-dives", "HowTo"),
    ("rabbit-strangulation-hammock-cord-risk", "strangulation risk from hammock cords", "care-deep-dives", "Article"),
    ("rabbit-rabbit-stuck-furniture-rescue", "rabbit stuck behind furniture, safe rescue", "care-deep-dives", "HowTo"),

    # ============= COMPARISONS (20) =============
    ("rabbit-vs-cavy-which-easier", "rabbit vs cavy, which is easier for first-time", "care-deep-dives", "Article"),
    ("rabbit-vs-cat-as-pet", "rabbit vs cat as a pet, side by side", "care-deep-dives", "Article"),
    ("rabbit-vs-hamster-as-pet", "rabbit vs hamster as a pet, time commitment", "care-deep-dives", "Article"),
    ("rabbit-vs-degu-as-pet", "rabbit vs degu, lesser-known comparison", "care-deep-dives", "Article"),
    ("rabbit-vs-chinchilla-as-pet", "rabbit vs chinchilla, what differs", "care-deep-dives", "Article"),
    ("rabbit-vs-dog-as-pet", "rabbit vs dog as a pet, the differences", "care-deep-dives", "Article"),
    ("rabbit-vs-rat-as-pet", "rabbit vs rat as a pet, intelligence", "care-deep-dives", "Article"),
    ("rabbit-vs-ferret-pet-comparison", "rabbit vs ferret as a pet comparison", "care-deep-dives", "Article"),
    ("rabbit-vs-budgie-care-time", "rabbit vs budgie care time", "care-deep-dives", "Article"),
    ("rabbit-vs-turtle-as-pet", "rabbit vs turtle, comparing care", "care-deep-dives", "Article"),
    ("rabbit-mini-lop-vs-netherland-dwarf", "mini lop vs netherland dwarf, side by side", "breed-specific-sg", "Article"),
    ("rabbit-lionhead-vs-jersey-wooly", "lionhead vs jersey wooly", "breed-specific-sg", "Article"),
    ("rabbit-flemish-vs-french-lop", "flemish giant vs french lop, large breeds", "breed-specific-sg", "Article"),
    ("rabbit-rex-vs-mini-rex", "rex vs mini rex, side by side", "breed-specific-sg", "Article"),
    ("rabbit-dutch-vs-himalayan", "dutch vs himalayan, marked breeds", "breed-specific-sg", "Article"),
    ("rabbit-petsafe-pen-vs-iris", "petsafe pen vs iris pen, side by side", "product-reviews", "Article"),
    ("rabbit-oxbow-vs-burgess-hay", "oxbow vs burgess hay brand comparison", "product-reviews", "Article"),
    ("rabbit-oxbow-vs-sherwood-pellets", "oxbow vs sherwood pellet brand comparison", "product-reviews", "Article"),
    ("rabbit-fresh-grass-vs-hay", "fresh grass vs hay for rabbits", "care-deep-dives", "Article"),
    ("rabbit-water-bottle-vs-bowl-revisit", "water bottle vs bowl revisited", "product-reviews", "Article"),

    # ============= COST / BUDGET (15) =============
    ("rabbit-monthly-cost-singapore-realistic", "realistic monthly rabbit cost in SG", "care-deep-dives", "Article"),
    ("rabbit-first-year-cost-breakdown", "first year cost breakdown for SG owners", "care-deep-dives", "Article"),
    ("rabbit-vet-visit-cost-by-purpose", "vet visit cost by purpose in SG", "vet-comparisons", "Article"),
    ("rabbit-emergency-fund-target-sg", "emergency fund target by breed in SG", "care-deep-dives", "Article"),
    ("rabbit-pet-insurance-rabbit-sg", "pet insurance for rabbits in SG, options", "vet-comparisons", "Article"),
    ("rabbit-cage-setup-cost-singapore", "cage setup cost in singapore, ranges", "care-deep-dives", "Article"),
    ("rabbit-cost-by-rabbit-age", "cost by rabbit age, young vs senior", "care-deep-dives", "Article"),
    ("rabbit-cost-saving-bulk-hay-sg", "cost saving with bulk hay purchases", "care-deep-dives", "Article"),
    ("rabbit-cost-saving-pellet-bulk", "cost saving with bulk pellet purchases", "care-deep-dives", "Article"),
    ("rabbit-spay-neuter-cost-cheapest-sg", "cheapest spay or neuter options in SG", "vet-comparisons", "Article"),
    ("rabbit-mid-tier-vs-premium-care", "mid-tier vs premium rabbit care, money", "care-deep-dives", "Article"),
    ("rabbit-adoption-vs-buying-cost", "adoption vs buying cost in SG", "care-deep-dives", "Article"),
    ("rabbit-replacing-pen-replacement-frequency", "replacing pens and cages, lifespan", "care-deep-dives", "Article"),
    ("rabbit-amazon-vs-local-shop-cost", "amazon vs local shop, true cost", "product-reviews", "Article"),
    ("rabbit-bulk-bedding-cost-sg", "bulk bedding cost in singapore", "product-reviews", "Article"),

    # ============= FIRST TIME OWNER (15) =============
    ("rabbit-before-you-get-rabbit-checklist", "before you get a rabbit, full checklist", "care-deep-dives", "Article"),
    ("rabbit-day-1-checklist-new-owner", "day 1 checklist for a new owner", "care-deep-dives", "HowTo"),
    ("rabbit-first-month-budget-tracker", "first month budget tracker for new owners", "care-deep-dives", "Article"),
    ("rabbit-mistakes-first-time-owners", "common first-time owner mistakes", "care-deep-dives", "Article"),
    ("rabbit-vs-stuffed-toy-research", "real rabbit vs stuffed toy research, do this first", "care-deep-dives", "Article"),
    ("rabbit-shopping-list-new-owner", "shopping list for a new rabbit owner", "care-deep-dives", "Article"),
    ("rabbit-first-vet-visit-questions", "first vet visit, questions to ask", "care-deep-dives", "Article"),
    ("rabbit-bringing-home-from-shelter", "bringing home from a shelter, the routine", "care-deep-dives", "HowTo"),
    ("rabbit-bringing-home-from-breeder", "bringing home from a breeder, the routine", "care-deep-dives", "HowTo"),
    ("rabbit-first-poop-issues-new-owner", "first poop issues a new owner faces", "care-deep-dives", "Article"),
    ("rabbit-first-night-noises-normal", "first night noises and what is normal", "care-deep-dives", "Article"),
    ("rabbit-first-month-vet-cadence", "first month vet cadence for new owners", "care-deep-dives", "Article"),
    ("rabbit-first-month-bond-building", "first month bond building plan", "care-deep-dives", "HowTo"),
    ("rabbit-introducing-to-family", "introducing a new rabbit to family", "care-deep-dives", "Article"),
    ("rabbit-family-rules-cleaning-feeding", "family rules for cleaning and feeding", "care-deep-dives", "Article"),

    # ============= GROOMING / CARE (15) =============
    ("rabbit-shedding-season-management", "shedding season management plan", "care-deep-dives", "HowTo"),
    ("rabbit-brush-types-coat-tested", "brush types per coat type, tested", "product-reviews", "Article"),
    ("rabbit-bath-no-bath-rules", "rabbits do not bathe, the rules", "care-deep-dives", "Article"),
    ("rabbit-bottom-spot-clean-method", "spot cleaning a dirty bottom", "care-deep-dives", "HowTo"),
    ("rabbit-nail-trim-step-by-step", "nail trim step by step at home", "care-deep-dives", "HowTo"),
    ("rabbit-nail-clipper-types-tested", "nail clipper types for rabbits, tested", "product-reviews", "Article"),
    ("rabbit-burrito-towel-handling", "the burrito towel for safe handling", "care-deep-dives", "HowTo"),
    ("rabbit-ear-cleaning-when-needed", "ear cleaning, when actually needed", "care-deep-dives", "Article"),
    ("rabbit-scent-glands-cleaning", "scent gland cleaning, the gentle way", "care-deep-dives", "HowTo"),
    ("rabbit-eye-gunk-cleaning-safe", "eye gunk cleaning, the safe method", "care-deep-dives", "HowTo"),
    ("rabbit-fur-mats-de-matting", "removing mats without injuring skin", "care-deep-dives", "HowTo"),
    ("rabbit-deshedding-tool-rabbit-warning", "deshedding tools, the rabbit warning", "care-deep-dives", "Article"),
    ("rabbit-coat-color-changes-mean", "coat color changes, what they mean", "care-deep-dives", "Article"),
    ("rabbit-static-cling-after-grooming", "static cling after grooming, fixing", "care-deep-dives", "Article"),
    ("rabbit-grooming-schedule-by-breed", "grooming schedule by breed", "care-deep-dives", "Article"),

    # ============= PRODUCTS BY BRAND (15) =============
    ("rabbit-oxbow-products-tested-sg", "oxbow products tested by SG owners", "product-reviews", "Article"),
    ("rabbit-burgess-products-availability-sg", "burgess product availability in SG", "product-reviews", "Article"),
    ("rabbit-sherwood-pellet-review-sg", "sherwood pellet review for SG", "product-reviews", "Article"),
    ("rabbit-kaytee-products-review", "kaytee products, are they ok", "product-reviews", "Article"),
    ("rabbit-supreme-tiny-friends-review", "supreme tiny friends farm review", "product-reviews", "Article"),
    ("rabbit-vitakraft-product-tested", "vitakraft products tested", "product-reviews", "Article"),
    ("rabbit-niteangel-products-review", "niteangel rabbit products review", "product-reviews", "Article"),
    ("rabbit-iris-pen-detailed-review", "iris pen detailed review for SG", "product-reviews", "Article"),
    ("rabbit-trixie-products-tested", "trixie rabbit products tested", "product-reviews", "Article"),
    ("rabbit-snuggle-safe-warmer-cold-only", "snuggle safe warmer, cold-care only", "product-reviews", "Article"),
    ("rabbit-savic-cage-review-sg", "savic cage review for SG buyers", "product-reviews", "Article"),
    ("rabbit-living-world-products-review", "living world products review", "product-reviews", "Article"),
    ("rabbit-marshall-pet-products-review", "marshall pet products review", "product-reviews", "Article"),
    ("rabbit-prevue-pet-products-review", "prevue pet rabbit products review", "product-reviews", "Article"),
    ("rabbit-amazon-rabbit-finds-tested", "amazon rabbit finds, tested in SG", "product-reviews", "Article"),

    # ============= EXERCISE / PLAY (10) =============
    ("rabbit-exercise-needs-by-age", "exercise needs by rabbit age", "care-deep-dives", "Article"),
    ("rabbit-zoom-room-setup-hdb", "zoom room setup in an HDB flat", "care-deep-dives", "HowTo"),
    ("rabbit-balcony-rabbit-safety-condo", "balcony rabbit safety in a condo", "care-deep-dives", "Article"),
    ("rabbit-outdoor-time-supervised-sg", "outdoor time supervised in SG conditions", "care-deep-dives", "Article"),
    ("rabbit-tracking-exercise-time-app", "tracking exercise time with an app", "care-deep-dives", "Article"),
    ("rabbit-play-fetch-with-rabbit", "play fetch with a rabbit, possible", "behaviour-troubleshooting", "Article"),
    ("rabbit-hide-and-seek-rabbit", "hide and seek with a rabbit, the game", "behaviour-troubleshooting", "Article"),
    ("rabbit-obstacle-course-build-home", "obstacle course at home for rabbits", "care-deep-dives", "HowTo"),
    ("rabbit-play-time-aggressive-channel", "channeling aggressive play time", "behaviour-troubleshooting", "Article"),
    ("rabbit-quiet-play-rainy-day-ideas", "quiet play ideas for rainy days", "care-deep-dives", "Article"),

    # ============= HANDLING / PICKUP (10) =============
    ("rabbit-pickup-safe-rabbit-spine", "safe pickup that protects the spine", "care-deep-dives", "HowTo"),
    ("rabbit-trance-state-stop", "rabbit trance state, why to stop using it", "care-deep-dives", "Article"),
    ("rabbit-football-hold-when-okay", "the football hold, when it is okay", "care-deep-dives", "Article"),
    ("rabbit-bunny-burrito-uses", "the bunny burrito and its uses", "care-deep-dives", "Article"),
    ("rabbit-from-cage-no-stress", "lifting from the cage with no stress", "care-deep-dives", "HowTo"),
    ("rabbit-from-floor-no-grab-tail", "from the floor without grabbing the tail", "care-deep-dives", "HowTo"),
    ("rabbit-children-rabbit-pickup-rules", "rules for children picking up rabbits", "care-deep-dives", "Article"),
    ("rabbit-pickup-after-injury", "picking up an injured rabbit safely", "care-deep-dives", "HowTo"),
    ("rabbit-pickup-aggressive-rabbit-method", "method for picking up an aggressive rabbit", "care-deep-dives", "HowTo"),
    ("rabbit-pickup-shy-rabbit-build-trust", "picking up a shy rabbit, build trust first", "care-deep-dives", "HowTo"),

    # ============= WHEN TO VET (10) =============
    ("rabbit-when-to-vet-vs-wait-checklist", "vet vs wait, the 24-hour checklist", "care-deep-dives", "Article"),
    ("rabbit-checklist-eye-issues", "vet checklist for eye issues", "care-deep-dives", "Article"),
    ("rabbit-checklist-not-eating", "vet checklist for not eating", "care-deep-dives", "Article"),
    ("rabbit-checklist-poop-change", "vet checklist for poop changes", "care-deep-dives", "Article"),
    ("rabbit-checklist-lethargy", "vet checklist for lethargy", "care-deep-dives", "Article"),
    ("rabbit-checklist-bumps-lumps", "vet checklist for bumps and lumps", "care-deep-dives", "Article"),
    ("rabbit-checklist-injury-fall", "vet checklist for injury or fall", "care-deep-dives", "Article"),
    ("rabbit-checklist-respiratory-issue", "vet checklist for respiratory issue", "care-deep-dives", "Article"),
    ("rabbit-checklist-behavior-change", "vet checklist for behavior change", "care-deep-dives", "Article"),
    ("rabbit-checklist-pre-bonding-vet", "vet checklist before bonding two rabbits", "care-deep-dives", "Article"),

    # ============= RECOVERY POST SURGERY (10) =============
    ("rabbit-post-spay-day-1-checklist", "post-spay day 1 home checklist", "care-deep-dives", "HowTo"),
    ("rabbit-post-spay-day-2-7-plan", "post-spay days 2 through 7 plan", "care-deep-dives", "HowTo"),
    ("rabbit-post-neuter-recovery-checklist", "post-neuter recovery checklist", "care-deep-dives", "HowTo"),
    ("rabbit-stitch-licking-prevention", "stitch licking prevention, gentle method", "care-deep-dives", "HowTo"),
    ("rabbit-cone-collar-rabbit-debate", "cone collar for rabbits, the debate", "care-deep-dives", "Article"),
    ("rabbit-recovery-feeding-syringe-plan", "syringe feeding plan during recovery", "care-deep-dives", "HowTo"),
    ("rabbit-recovery-pain-signs-watch", "pain signs to watch during recovery", "care-deep-dives", "Article"),
    ("rabbit-recovery-litter-changes", "litter setup changes during recovery", "care-deep-dives", "HowTo"),
    ("rabbit-recovery-bonded-pair-together", "keeping a bonded pair together during recovery", "care-deep-dives", "Article"),
    ("rabbit-recovery-incision-photos", "incision recovery photos by day", "care-deep-dives", "Article"),

    # ============= MISC / FILLER (5) =============
    ("rabbit-pet-rabbit-history-domestication", "history of rabbit domestication, briefly", "care-deep-dives", "Article"),
    ("rabbit-anatomy-quick-tour-owners", "anatomy quick tour for new owners", "care-deep-dives", "Article"),
    ("rabbit-lifespan-by-breed-realistic", "lifespan by breed, realistic figures", "care-deep-dives", "Article"),
    ("rabbit-vision-color-perception", "rabbit vision and color perception", "care-deep-dives", "Article"),
    ("rabbit-hearing-frequency-range", "rabbit hearing frequency range", "care-deep-dives", "Article"),
]


def main():
    # collect existing slugs
    existing_slugs = set()
    for p in GUIDES.glob("*.mdx"):
        existing_slugs.add(p.stem)

    queue = json.loads(QUEUE.read_text())
    queued_keys = {t["key"] for t in queue["topics"]}

    added = 0
    skipped = 0
    seen_in_seed = set()

    for key, title, stream, schema_type in TOPICS:
        if key in existing_slugs:
            print(f"skip (guide exists): {key}")
            skipped += 1
            continue
        if key in queued_keys:
            print(f"skip (already queued): {key}")
            skipped += 1
            continue
        if key in seen_in_seed:
            print(f"skip (dupe in seed): {key}")
            skipped += 1
            continue
        seen_in_seed.add(key)
        queue["topics"].append({
            "key": key,
            "stream": stream,
            "title": title,
            "status": "queued",
            "schema_type": schema_type,
        })
        added += 1

    QUEUE.write_text(json.dumps(queue, indent=2) + "\n")
    print(f"\nadded: {added}")
    print(f"skipped: {skipped}")
    print(f"total in seed: {len(TOPICS)}")
    print(f"new queue size: {len(queue['topics'])}")


if __name__ == "__main__":
    main()
